// Generates src/design/tokens.css from src/design/tokens.json (W3C DTCG format).
// `--check` exits non-zero when the committed CSS is out of date (used in CI).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, 'src/design/tokens.json');
const target = resolve(root, 'src/design/tokens.css');
const tokens = JSON.parse(readFileSync(source, 'utf8'));

const flat = new Map();
function walk(node, path) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (value && typeof value === 'object' && '$value' in value) {
      flat.set([...path, key].join('.'), value.$value);
    } else if (value && typeof value === 'object') {
      walk(value, [...path, key]);
    }
  }
}
walk(tokens, []);

function resolveValue(value, seen = new Set()) {
  if (Array.isArray(value)) {
    return value.map((v) => (/\s/.test(v) ? `"${v}"` : v)).join(', ');
  }
  if (typeof value !== 'string') return String(value);
  const alias = /^\{([^}]+)\}$/.exec(value);
  if (!alias) return value;
  const ref = alias[1];
  if (seen.has(ref)) throw new Error(`Circular token alias: ${ref}`);
  if (!flat.has(ref)) throw new Error(`Unknown token alias: ${ref}`);
  return resolveValue(flat.get(ref), new Set([...seen, ref]));
}

const lines = [...flat.keys()].map((name) => `  --pc-${name.replaceAll('.', '-')}: ${resolveValue(flat.get(name))};`);
const css = `/* Generated by scripts/build-tokens.mjs from tokens.json. Do not edit by hand. */\n:root {\n${lines.join('\n')}\n}\n`;

if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== css) {
    console.error('tokens.css is out of date. Run `npm run tokens` and commit the result.');
    process.exit(1);
  }
  console.log(`tokens.css is up to date (${flat.size} tokens).`);
} else {
  writeFileSync(target, css);
  console.log(`Wrote ${flat.size} tokens to src/design/tokens.css`);
}
